# Generated by Django 3.2.3 on 2022-01-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
