# Generated by Django 3.2.3 on 2022-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220110_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(default=123654, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.AutoField(default=32456, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
