# Generated by Django 3.2.11 on 2022-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220110_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cold_storage',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cs_name', models.CharField(max_length=40)),
                ('cs_adr', models.CharField(max_length=50)),
                ('cs_email', models.CharField(max_length=40)),
                ('cs_mobile', models.CharField(max_length=10)),
                ('cs_password', models.CharField(max_length=20)),
                ('cs_max_str', models.CharField(max_length=70)),
                ('cs_avl_str', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default=123, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
