# Generated by Django 3.2.11 on 2022-01-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220110_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=40)),
                ('f_adr', models.CharField(max_length=50)),
                ('f_email', models.CharField(max_length=40)),
                ('f_mobile', models.CharField(max_length=10)),
                ('f_gender', models.CharField(max_length=6)),
                ('f_age', models.CharField(max_length=3)),
                ('f_occupation', models.CharField(max_length=20)),
                ('f_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=40)),
                ('r_adr', models.CharField(max_length=50)),
                ('r_email', models.CharField(max_length=40)),
                ('r_mobile', models.CharField(max_length=10)),
                ('r_gender', models.CharField(max_length=6)),
                ('r_age', models.CharField(max_length=3)),
                ('r_occupation', models.CharField(max_length=20)),
                ('r_password', models.CharField(max_length=20)),
            ],
        ),
    ]
