# Generated by Django 3.2.11 on 2022-01-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_farmer_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cold_storage',
            name='cs_pname',
            field=models.CharField(default=122, max_length=40),
            preserve_default=False,
        ),
    ]
