# Generated by Django 3.2.11 on 2022-01-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cold_storage_cs_pname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
        migrations.RemoveField(
            model_name='cold_storage',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='cold_storage',
            name='cs_adr',
        ),
        migrations.RemoveField(
            model_name='cold_storage',
            name='cs_email',
        ),
        migrations.RemoveField(
            model_name='cold_storage',
            name='cs_mobile',
        ),
        migrations.RemoveField(
            model_name='cold_storage',
            name='cs_name',
        ),
        migrations.RemoveField(
            model_name='cold_storage',
            name='cs_password',
        ),
        migrations.AddField(
            model_name='cold_storage',
            name='cs_own',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cold_storage',
            name='id',
            field=models.BigAutoField(auto_created=True, default=255, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
