# Generated by Django 3.2.11 on 2022-01-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220112_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cold_storage',
            name='cs_avl_str',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cold_storage',
            name='cs_max_str',
            field=models.IntegerField(),
        ),
    ]
