# Generated by Django 3.2.11 on 2022-01-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220113_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cs_name',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
